version: '3'
services:
  db: 
    image: postgres:9.6.15-alpine
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=john
      - POSTGRES_PASSWORD=pwd0123456789
      - POSTGRES_DB=mydb
    ports:
      - 54320:5432
  api:
    build: ./api  
    restart: always
    environment: 
      - PORT=3000
      - DB='postgres://john:pwd0123456789@db:5432/mydb'
    ports:
      - 3000:3000
    links:
      - db
  web: 
    build: ./web
    environment:
      - PORT=3001
      - API_HOST=http://0.0.0.0:3000
    links:
      - api
    ports:
      - 3001:3001
