version: '3'
services:
  db: 
    image: postgres:alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER='john'
      - POSTGRES_PASSWORD='la'
      - POSTGRES_DB='mydb'
  api:
    build: ./api  
    restart: always
    environment: 
      - PORT=3000
      - DB='postgres://john:la@db:5432/mydb'
    ports:
      - 3000:3000
    links:
      - db
  web: 
    build: ./web
    environment:
      - PORT=3001
      - API_HOST=http://api:3000
    links:
      - api
    ports:
      - 3001:3001

volumes:
  db: